// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, provider, access_token, password_hash) 
VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, provider, access_token, password_hash, created_at, updated_at
`

type CreateAccountParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Provider     string      `json:"provider"`
	AccessToken  pgtype.Text `json:"access_token"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Provider,
		arg.AccessToken,
		arg.PasswordHash,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccessToken,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, primary_email) 
    VALUES ($1, $2)
RETURNING id, name, primary_email, created_at, updated_at
`

type CreateUserParams struct {
	Name         pgtype.Text `json:"name"`
	PrimaryEmail pgtype.Text `json:"primary_email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.PrimaryEmail)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccounts = `-- name: GetUserAccounts :many
SELECT id, user_id, provider, access_token, password_hash, created_at, updated_at FROM accounts
WHERE user_id = $1
`

func (q *Queries) GetUserAccounts(ctx context.Context, userID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, getUserAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.AccessToken,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, primary_email, created_at, updated_at FROM users
WHERE primary_email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, primaryEmail pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, primaryEmail)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, primary_email, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
