// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Provider     string
	AccessToken  pgtype.Text
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PrimaryEmail pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
